# National Veterans Organization

In [1]:
import pandas as pd
import numpy as np

In [4]:
learn = pd.read_csv('cup98LRN.txt')
valid = pd.read_csv('cup98VAL.txt')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
boolean_mask = learn.loc[:, "TARGET_D"] != 0.0
len(learn[boolean_mask])

4843

In [5]:
valid.head(10)

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,CONTROLN,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,9301,PV3,0,WI,53558,,,1702,0,X,...,188946,1,L,1,G,X,X,X,15.0,B
1,9501,CNT,0,TX,78501,,,1501,0,,...,126296,1,L,1,F,X,X,X,13.0,B
2,9101,L01,1,CA,92392,,,3001,0,,...,155244,1,L,1,G,X,X,X,34.0,A
3,9401,HAM,0,TX,77625-,,,4909,0,,...,123985,0,L,1,F,X,X,X,58.0,B
4,9201,NAS,2,TX,76051,,,5406,0,,...,119118,1,L,3,E,X,X,X,2.0,A
5,8601,WKB,2,CO,80011,,P,3701,0,,...,10120,1,L,1,G,X,X,X,50.0,B
6,9601,ARB,1,IN,46074,,,6601,0,,...,59465,1,L,1,F,X,X,X,43.0,B
7,8801,FRC,2,WI,54469,,,1203,0,,...,80803,0,L,3,D,X,X,X,39.0,C
8,9601,ARG,0,MO,63141,,,3201,0,,...,2824,0,L,1,F,X,X,X,3.0,A
9,9601,MWD,0,CA,90280,,,5901,0,,...,145014,0,L,1,F,X,X,X,28.0,A